# version: '3.8'
services:
  db:
    container_name: "webapp_db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "RestAPI_DB"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"